# Generated by Django 3.2.12 on 2023-10-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='car_model',
        ),
    ]
