# Generated by Django 3.2.12 on 2023-10-10 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_orders_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_amount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
