# Generated by Django 3.2.12 on 2023-10-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_orders_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='car_variant',
        ),
    ]
