# Generated by Django 3.2.12 on 2023-10-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20231013_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
    ]
