# Generated by Django 3.2.12 on 2023-10-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20231014_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carcolor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carmodel'),
        ),
    ]
