# Generated by Django 3.2.12 on 2023-10-20 10:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20231014_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='booking_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='orders',
            name='booking_source',
            field=models.CharField(default='Seres', max_length=150),
        ),
        migrations.AddField(
            model_name='orders',
            name='prebooking_amount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orders',
            name='walkin_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkin'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
