# Generated by Django 3.2.12 on 2023-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20231020_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='car_model',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='Full', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='booking_source',
            field=models.CharField(default='Showroom', max_length=150),
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
