# Generated by Django 3.2.12 on 2023-11-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangevehicle',
            name='license_plate',
            field=models.CharField(max_length=100, unique='True'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
