# Generated by Django 3.2.12 on 2023-11-20 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20231102_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='booking_amount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
