# Generated by Django 3.2.12 on 2023-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_orders_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
