# Generated by Django 3.2.12 on 2023-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_orders_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
