# Generated by Django 3.2.12 on 2023-11-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_orders_date_of_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_source', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='booking_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookingsource'),
        ),
    ]
